# Generated by Django 5.0.4 on 2024-05-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categorys'},
        ),
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name': 'Receita', 'verbose_name_plural': 'Receitas'},
        ),
        migrations.AlterField(
            model_name='receita',
            name='cover',
            field=models.ImageField(upload_to='receitas/covers/%Y/%m/%d/'),
        ),
    ]
